id: I501A1910
legacy_id: P004590
ocr_import_info:
  bdrc_scan_id: W25105
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T14:05:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:00:30.039072+00:00'
last_modified: 2022-09-02 14:00:48.672644
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25105
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW25105
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕགས་མཆོག་ཐུགས་རྗེ་ཆེན་པོའི་སྤྲུལ་པ་ཆོས་རྒྱལ་དྲི་མེད་ཀུན་ལྡན་ལེགས་པའི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྔགས་འོས་བསྔགས་པ།
  author: སྨན་རི་བ་བློ་བཟང་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.7712114234021396
  ocr_word_median_confidence_index: 0.8700000047683716
quality: null
bases:
  I3858:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3858
      total_pages: 288
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3858.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7712114234021396
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
