id: P004590
initial_creation_type: ocr
source_metadata:
  id: bdr:W25105
  title: འཕགས་མཆོག་ཐུགས་རྗེ་ཆེན་པོའི་སྤྲུལ་པ་ཆོས་རྒྱལ་དྲི་མེད་ཀུན་ལྡན་ལེགས་པའི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྔགས་འོས་བསྔགས་པ
  author: ''
  volumes: {}
