id: P004590
initial_creation_type: ocr
source_metadata:
  id: bdr:W25105
  title: འཕགས་མཆོག་ཐུགས་རྗེ་ཆེན་པོའི་སྤྲུལ་པ་ཆོས་རྒྱལ་དྲི་མེད་ཀུན་ལྡན་ལེགས་པའི་བློ་གྲོས་ཀྱི་རྟོགས་བརྗོད་སྔགས་འོས་བསྔགས་པ
  author: ''
  volumes:
    ea3937269a4948a7acf4a2c8542ac6fb:
      image_group_id: I3858
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
